- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: git-key
    secret:
      secretName: git-key
      defaultMode: 0400
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: git-key
    mountPath: /etc/fluxd/ssh
    readOnly: true
- op: add
  path: /spec/template/spec/serviceAccountName
  value: flux-helm-operator
