apiVersion: v1
repositories:
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/stable-index.yaml
    certFile: ""
    keyFile: ""
    name: stable
    password: ""
    url: https://kubernetes-charts.storage.googleapis.com
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/incubator-index.yaml
    certFile: ""
    keyFile: ""
    name: incubator
    password: ""
    url: https://kubernetes-charts-incubator.storage.googleapis.com
    username: ""